import { useState } from 'react'
import { Share2, Copy, Check } from 'lucide-react'
import toast from 'react-hot-toast'

export default function ShareButton({ roadmap }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    if (!roadmap) return

    const lines = [
      `📚 ${roadmap.title || roadmap.skill + ' Learning Roadmap'}`,
      `Level: ${roadmap.level} | ${roadmap.durationDays} days | ${roadmap.dailyHours}h/day`,
      '',
    ]

    roadmap.weeks?.forEach(week => {
      lines.push(`── Week ${week.week}: ${week.goal} ──`)
      week.days?.forEach(day => {
        lines.push(`  Day ${day.day}: ${day.topic}`)
        lines.push(`    Task: ${day.task}`)
        if (day.resource) lines.push(`    Resource: ${day.resource}`)
      })
      lines.push('')
    })

    lines.push('Generated by PathGen AI – IIT Patna Capstone 2026')

    navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    toast.success('Roadmap copied to clipboard!')
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <button
      onClick={handleCopy}
      disabled={!roadmap}
      className="btn-secondary flex items-center gap-2 text-sm disabled:opacity-50 disabled:cursor-not-allowed"
    >
      {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
      {copied ? 'Copied!' : 'Copy Roadmap'}
    </button>
  )
}
